/**
\brief Register map and driver API for the Bosch BMP388 pressure sensor.

The driver follows the register interface described in the BMP388 datasheet
and mirrors the function layout of the existing BMX160 driver.

\author Generated by GitHub Copilot, Oct 2025.
*/

#ifndef __BMP388_H__
#define __BMP388_H__

#include <stdint.h>
#include <stdbool.h>

//=========================== define =========================================

#ifndef BMP388_I2C_ADDR
#define BMP388_I2C_ADDR          0x76u   ///< Adjust according to SDO wiring (0x76 or 0x77).
#endif

// Register addresses
#define BMP388_REG_CHIP_ID       0x00u
#define BMP388_REG_ERR_REG       0x02u
#define BMP388_REG_STATUS        0x03u
#define BMP388_REG_DATA_P_XLSB   0x04u
#define BMP388_REG_DATA_P_LSB    0x05u
#define BMP388_REG_DATA_P_MSB    0x06u
#define BMP388_REG_DATA_T_XLSB   0x07u
#define BMP388_REG_DATA_T_LSB    0x08u
#define BMP388_REG_DATA_T_MSB    0x09u
#define BMP388_REG_SENSORTIME_0  0x0Cu
#define BMP388_REG_SENSORTIME_1  0x0Du
#define BMP388_REG_SENSORTIME_2  0x0Eu
#define BMP388_REG_EVENT         0x10u
#define BMP388_REG_INT_STATUS    0x11u
#define BMP388_REG_FIFO_LENGTH_0 0x12u
#define BMP388_REG_FIFO_LENGTH_1 0x13u
#define BMP388_REG_FIFO_DATA     0x14u
#define BMP388_REG_PWR_CTRL      0x1Bu
#define BMP388_REG_OSR           0x1Cu
#define BMP388_REG_ODR           0x1Du
#define BMP388_REG_CONFIG        0x1Fu
#define BMP388_REG_INT_CTRL      0x19u
#define BMP388_REG_FIFO_CONFIG_1 0x17u
#define BMP388_REG_FIFO_CONFIG_2 0x18u
#define BMP388_REG_CMD           0x7Eu

#define BMP388_REG_CALIB_DATA    0x31u
#define BMP388_REG_CALIB_LENGTH  21u

// Command register values
#define BMP388_CMD_SOFT_RESET    0xB6u

// Power control bits
#define BMP388_PWR_CTRL_PRESS_EN (1u << 0)
#define BMP388_PWR_CTRL_TEMP_EN  (1u << 1)
#define BMP388_PWR_CTRL_MODE_POS 4u
#define BMP388_PWR_CTRL_MODE_MASK (0x03u << BMP388_PWR_CTRL_MODE_POS)
#define BMP388_PWR_CTRL_MODE_SLEEP  (0x00u << BMP388_PWR_CTRL_MODE_POS)
#define BMP388_PWR_CTRL_MODE_FORCED (0x01u << BMP388_PWR_CTRL_MODE_POS)
#define BMP388_PWR_CTRL_MODE_NORMAL (0x03u << BMP388_PWR_CTRL_MODE_POS)

// Oversampling helpers (OSR register)
#define BMP388_OSR_PRESS(x)      ((uint8_t)((x) & 0x07u))
#define BMP388_OSR_TEMP(x)       ((uint8_t)(((x) & 0x07u) << 3))

// IIR filter coefficient encoding (CONFIG register bits[2:0])
#define BMP388_IIR_COEFF_OFF     0x00u
#define BMP388_IIR_COEFF_1       0x01u
#define BMP388_IIR_COEFF_3       0x02u
#define BMP388_IIR_COEFF_7       0x03u
#define BMP388_IIR_COEFF_15      0x04u
#define BMP388_IIR_COEFF_31      0x05u
#define BMP388_IIR_COEFF_63      0x06u
#define BMP388_IIR_COEFF_127     0x07u

//=========================== typedef ========================================

typedef struct {
    double par_t1;
    double par_t2;
    double par_t3;

    double par_p1;
    double par_p2;
    double par_p3;
    double par_p4;
    double par_p5;
    double par_p6;
    double par_p7;
    double par_p8;
    double par_p9;
    double par_p10;
    double par_p11;

    double t_lin;
} bmp388_calibration_t;

//=========================== public =========================================

/** Initialize the BMP388, fetch calibration data and enter normal mode. */
bool bmp388_init(void);

/** Issue a soft reset and wait until the device is ready. */
void bmp388_soft_reset(void);

/** Read the CHIP_ID register (expected 0x50). */
uint8_t bmp388_who_am_i(void);

/**
 * Configure oversampling, IIR filter coefficient and output data rate.
 * Parameters follow datasheet encodings (0-7 for oversampling, 0-255 for ODR).
 */
void bmp388_configure(uint8_t osr_pressure, uint8_t osr_temperature, uint8_t odr, uint8_t iir_coeff);

/** Trigger a single conversion in forced mode. */
void bmp388_trigger_forced_measurement(void);

/** Read the raw 24-bit pressure and temperature samples. */
void bmp388_read_uncompensated(uint32_t *pressure_raw, uint32_t *temperature_raw);

/** Update cached compensated pressure (Pa) and temperature (°C). */
void bmp388_update_measurement(void);

/** Return the last computed temperature in °C. */
float bmp388_get_temperature_c(void);

/** Return the last computed pressure in Pa. */
float bmp388_get_pressure_pa(void);

/** Compute altitude above sea level in meters using the barometric formula. */
float bmp388_get_altitude_m(float sea_level_pa);

#endif /* __BMP388_H__ */
